
# Azure OpenAI API parameters
PROMPT_TEMPLATE_FORMAT = 'jinja2'
OPENAI_MODEL_NAME = 'gpt-4o'
OPENAI_TEMPERATURE = 1e-16
OPENAI_API_TYPE = 'azure'
OPENAI_API_VERSION = '2024-02-01'
OPENAI_DEPLOYMENT_NAME = 'lunar-chatgpt-4o'
OPENAI_TOP_P = 1e-16
OPENAI_SEED = 1234
